### ISSUE TITLE
Galleries?

### ISSUE THREAD

**Issue by Shaav** [rolyli/lonk-dl#6]
Not sure if you're still working on this project... wondering if adding support for galleries is realistic?

**Comment by rolyli** [comment]
Hey, thanks for taking interest. I'll have a look and see if I can add it!

**Comment by rolyli** [comment]
PRAW doesn't yet support Reddit galleries. I've tried to crawl through the actual gallery images but it's a difficult issue for me. Sorry but I won't be able to implement this feature.

**Comment by Shaav** [comment]
Thanks for looking into it! Appreciated!
